CREATE TABLE task (
  id BIGINT AUTO_INCREMENT NOT NULL,
   title VARCHAR(255) NULL,
   `description` VARCHAR(255) NULL,
   user_id BIGINT NULL,
   CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task ADD CONSTRAINT FK_TASK_ON_USER FOREIGN KEY (user_id) REFERENCES user (id);